name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "Iniciando login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Fin del login"
      - name: Build docker image
        run: |
          docker build -t angelx105/docker-graphql:1.0.0 .
          docker build -t angelx105/docker-graphql .
      - name: Push docker image
        run: |
          docker push angelx105/docker-graphql:1.0.0
          docker push angelx105/docker-graphql
